# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 739f1172543122364e3f303c5e9aea056d907f3f1b596b4fc60a47122d37a5f104baf4e69ccfd699b2a5eaf0a0b8c277c6d4b34890d1cb829f334a7401ff42f0

test:
  secret_key_base: 9f8c9e1627e845a9a43f1e7421d382d2262406e07146b21668eaa4afab733ade74dbba6f63a7ecdd3adeee1e83a6ebd90ece06b989168a95ad5029cd2e54aa98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
